vich_uploader:
    db_driver: orm
    mappings:
        user_images:
            uri_prefix: /uploads/profile_pictures
            upload_destination: '%kernel.project_dir%/assets/imgs/profile_pictures'
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: false